# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-24 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, help_text='Name for the article. Max 64 characters.', max_length=64, unique=True)),
                ('slug', models.SlugField(help_text='Short name for use in urls.', unique=True)),
                ('summary', models.CharField(help_text='Teaser for explaination of the content. Max 400 characters.', max_length=400)),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='date created.')),
                ('mod_date', models.DateTimeField(auto_now_add=True, verbose_name='date last modified.')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published.')),
                ('body', models.TextField(blank=True, default='', help_text='Main text of article. Max 8000 characters.', max_length=8000)),
                ('author', models.CharField(blank=True, default='', help_text='Name of the author.', max_length=64)),
            ],
        ),
    ]
